#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mรอสักครู่ \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mรอสักครู่ \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m สำเร็จ !\033[1;37m"

tput cnorm

}

echo " "

fun_atts () {

  [[ -e /home/versao ]] && rm /home/versao

  [[ -e /tmp/att ]] && rm /tmp/att

	wget -c -P /home https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/versao

	[[ -f "/home/versao" ]] && mv /home/versao /tmp/att

	[[ ! -e /bin/versao ]] && rm -rf /bin/menu

} > /dev/null 2>&1

echo -e "                              \033[1;31mโดย Crazy\033[1;36m"

echo -e "   SSHPlus" | figlet

echo " "

echo -e "   \033[1;32mกำลังตรวจสอบการอัปเดตที่มี\033[0m\n"

fun_bar 'fun_atts'

[[ ! -f "/tmp/att" ]] && {

	echo -e "\n\033[1;31mเกิดข้อผิดพลาดในการเชื่อมต่อกับเซิร์ฟเวอร์\n"

	echo -ne "\033[1;31m กด \033[1;33mEnter \033[1;32mเพื่อกลับสู่ \033[1;32mเมนู!\033[0m"; read

	menu

}

echo " "

vrs1=$(sed -n '1 p' /bin/versao| sed -e 's/[^0-9]//ig')

vrs2=$(sed -n '1 p' /tmp/att | sed -e 's/[^0-9]//ig')

[[ "$vrs1" == "$vrs2" ]] && {

  echo -e " \033[1;36m     สคริปต์นี้เป็นเวอร์ชันล่าสุดแล้ว!\033[1;32m\n"

  rm /tmp/att > /dev/null 2>&1

  echo -e " \033[1;33mข้อมูลเพิ่มเติม \033[1;31m(โทรเลขแกรม): \033[1;37m@AAAAAEXQOSyIpN2JZ0ehUQ\n"

  echo -ne " \033[1;31mกด \033[1;33mEnter \033[1;32mเพื่อกลับสู่ \033[1;32mเมนู!\033[0m"; read

  menu

} || {

  echo -e "  \033[1;36mมีการอัปเดตใหม่ที่สามารถใช้ได้!\033[1;33m\n"

  echo -e "  \033[1;33mข้อมูลเพิ่มเติม \033[1;31m(โทรเลขแกรม): \033[1;37m@AAAAAEXQOSyIpN2JZ0ehUQ\n"

  echo -e "  \033[1;32mรายละเอียดของการอัปเดต:\033[0m\n"

  while read บรรทัด; do

    echo -e "  \033[1;37m- \033[1;33m$บรรทัด"

  done < "/tmp/att"

  echo " "

  echo -ne "  \033[1;32mคุณต้องการอัปเดตหรือไม่ \033[1;31m? \033[1;33m[y/n]:\033[1;37m "; read res

  if [[ "$res" = y || "$res" = Y ]];then

    echo -e "\n\033[1;32m  กำลังเริ่มอัปเดต..."

    sleep 3

    wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Plus > /dev/null 2>&1

    chmod +x Plus

    ./Plus

    clear

    echo -e "\033[1;32mสคริปต์ได้รับการอัปเดตเรียบร้อยแล้ว\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31mกด \033[1;33mEnter \033[1;32mเพื่อกลับสู่ \033[1;32mเมนู!\033[0m"; read

    menu

  else

    menu

  fi

}